# Enhance MagIC file for Shaat dike data

Two MagIC files are generated from project research:
- The set of MagIC files exported from Demag_GUI associated with the thermal demagnetization data
- The MagIC file exported from the IRM database associated with the rock magnetic experiments

These files need to be merged together into a single contribution as was done in:
https://github.com/Swanson-Hysell-Group/2021_ECMB/blob/main/data/rockmag_pmag_MagIC/combine_MagIC.ipynb

## Import Python packages

In [1]:
import pmagpy.ipmag as ipmag
import pmagpy.pmag as pmag
import pmagpy.contribution_builder as cb
import pandas as pd
import numpy as np
import json
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import shutil

pmag_rmag_dir = '../data/pmag'

## Paleomagnetic data

The data that have been analyzed using demag_gui with MagIC files being saved out of demag_gui are imported below.

In [2]:
pmag_dir_path = '../data/pmag/demag'
pmag_contribution = cb.Contribution(pmag_dir_path)
pmag_measurements = pmag_contribution.tables['measurements'].df
pmag_specimens = pmag_contribution.tables['specimens'].df
pmag_samples = pmag_contribution.tables['samples'].df
pmag_sites = pmag_contribution.tables['sites'].df
pmag_locations = pmag_contribution.tables['locations'].df

-I- Using online data model

-I- Getting method codes from earthref.org

-I- Using cached vocabularies

-I- Using cached suggested vocabularies

In [3]:
pmag_specimens.head()

,specimen,experiments,sample,dir_alpha95,dir_comp,dir_dec,dir_inc,dir_n_comps,dir_n_measurements,dir_tilt_correction,dir_dang,dir_mad_free,meas_step_max,meas_step_min,meas_step_unit,analysts,instrument_codes,software_packages,int_corr,citations,method_codes,result_quality,volume,weight,location,site
specimen name,,,,,,,,,,,,,,,,,,,,,,,,,,
AynC-1,AynC-1,NaN,AynC-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This study,LP-NOMAG,NaN,NaN,NaN,Zalawt plain,AynC
AynC-1,AynC-1,AynC-1_LP-DIR-T,AynC-1,NaN,lt,206.4,68.7,2.0,8.0,-1.0,8.6,1.0,573.0,273.0,K,NaN,hargrave 2023-10-15 17:59:17,pmagpy-4.2.125: demag_gui,u,This study,LP-DIR-T:DE-BFL:DA-DIR,g,NaN,NaN,Zalawt plain,AynC
AynC-1,AynC-1,AynC-1_LP-DIR-T,AynC-1,NaN,mag,327.1,-65.8,2.0,12.0,-1.0,0.0,2.0,863.0,783.0,K,NaN,hargrave 2023-10-15 17:59:17,pmagpy-4.2.125: demag_gui,u,This study,LP-DIR-T:DE-BFL-A:DA-DIR,g,NaN,NaN,Zalawt plain,AynC
AynC-1,AynC-1,AynC-1_LP-DIR-T,AynC-1,NaN,lt,2.8,23.9,2.0,8.0,0.0,8.6,1.0,573.0,273.0,K,NaN,hargrave 2023-10-15 17:59:17,pmagpy-4.2.125: demag_gui,u,This study,LP-DIR-T:DE-BFL:DA-DIR-GEO,g,NaN,NaN,Zalawt plain,AynC
AynC-1,AynC-1,AynC-1_LP-DIR-T,AynC-1,NaN,mag,207.2,-25.0,2.0,12.0,0.0,0.0,2.0,863.0,783.0,K,NaN,hargrave 2023-10-15 17:59:17,pmagpy-4.2.125: demag_gui,u,This study,LP-DIR-T:DE-BFL-A:DA-DIR-GEO,g,NaN,NaN,Zalawt plain,AynC

### Paleomagnetic sites 

#### Enhance the site location precision and add site metadata

An issue with the CIT data format is that the precision on the site longitude/latitude is low given the ASCII file format. We therefore need to bring in more precise locations which are within the site_locations.csv file and add them to the site table.

Additionally, MagIC requires that sites have additional metadata including:
- geologic_classes
- geologic_types
- lithologies
- age (or age_high and age_low)
- age_unit
  
These metadata are within the site_locations.csv file are can be merged into the sites table in the code below.

In [4]:
# get more precise site locations
SD_site_locations = pd.read_csv('../data/field_data/site_locations.csv', sep=',', header=0, index_col='site')
# map site locations to site data
pmag_sites['lat'] = SD_site_locations['latitude'][pmag_sites['site']].tolist()
pmag_sites['lon'] = SD_site_locations['longitude'][pmag_sites['site']].tolist()
pmag_sites['geologic_classes'] = SD_site_locations['geologic_classes'][pmag_sites['site']].tolist()
pmag_sites['geologic_types'] = SD_site_locations['geologic_types'][pmag_sites['site']].tolist()
pmag_sites['lithologies'] = SD_site_locations['lithologies'][pmag_sites['site']].tolist()
pmag_sites['age_high'] = SD_site_locations['age_high'][pmag_sites['site']].tolist()
pmag_sites['age_low'] = SD_site_locations['age_low'][pmag_sites['site']].tolist()
pmag_sites['age_unit'] = SD_site_locations['age_unit'][pmag_sites['site']].tolist()

The sites that do not have a site mean calculated for them in Pmag_GUI do not have a citation generated. Here we fill in those `None` values with 'This study'

In [5]:
pmag_sites['citations'] = pmag_sites['citations'].fillna('This study')

All site locations were determined with GPS and that should be added to the method codes. The code below appends that to the existing method codes or puts that in as the single method codes if they are not yet other method codes.

In [6]:
pmag_sites['method_codes'] = pmag_sites['method_codes'].apply(lambda x: 'FS-LOC-GPS' if pd.isna(x) else x + ':FS-LOC-GPS')

The criteria column in the sites is not used for this data set so will be dropped.

In [7]:
pmag_sites = pmag_sites.drop(columns=['criteria'])

#### Filter out tilt-corrected specimens and sites when not in Leger panel

We only have strong structural control in the Leger panel. We exported both geographic and tilt-corrected coordinates for every specimen and site out of Pmag_GUI, but should only report tilt-corrected data (dir_tilt_correction of 100) for the Leger panel. We can find the sites within the Leger panel and only keep pmag_specimens and pmag_sites with ['dir_tilt_correction'] of 100 for those sites.

All specimens keep their directions in specimen coordinates (dir_tilt_correction of -1) and geographic coordinates (dir_tilt_correction of 0), and specimens that were measured but not interpreted (no dir_tilt_correction) are kept so that every measurement has its specimen.

In [8]:
leger_sites = SD_site_locations[SD_site_locations['locale'].str.contains("Leger", na=False)].index
leger_sites

Index(['SD36', 'SD37', 'SD38', 'SD39', 'SD40', 'SD42', 'SD43', 'SD44', 'SD45',
       'SD46', 'SD47', 'SD48', 'SD49', 'SD50', 'SD51', 'SD52', 'SD53', 'SD54',
       'SD55', 'SD56', 'SD57', 'SD58', 'SD59', 'SD60', 'SD61', 'SD62', 'SD63',
       'SD64', 'SD65', 'SD66', 'SD67', 'SD68', 'SD69', 'SD70', 'SD71', 'SD72',
       'SD73', 'SD74', 'SD75', 'SD76', 'SD77', 'SD78', 'SD79', 'SD80', 'SD86',
       'SD87', 'SD88', 'SD89', 'SD90', 'SD91', 'SD92', 'SD93', 'SD94', 'SD95',
       'SD96', 'SD97', 'SD98', 'SD99', 'S100', 'S101', 'S102', 'S103', 'S104',
       'S105', 'S106', 'S107'],
      dtype='str', name='site')

We are going to filter the sites table so that it has geographic for all sites and tilt corrected for the Leger panel. We also need to include a few extra sites that don't have site means, but that have samples in the samples table.

In [9]:
extra_sites = ["SD76", "SD15", "S102", "SD98", "S105", "SD66", "SD73"]

In [10]:
mask = (
    (pmag_sites["dir_tilt_correction"] == 0)
    | (
        (pmag_sites["dir_tilt_correction"] == 100)
        & pmag_sites["site"].isin(leger_sites)
    )
    | pmag_sites["site"].isin(extra_sites)
)

pmag_sites = pmag_sites[mask].copy()

pmag_specimens = pmag_specimens[
    pmag_specimens["dir_tilt_correction"].isna()
    | pmag_specimens["dir_tilt_correction"].isin([-1, 0])
    | (
        (pmag_specimens["dir_tilt_correction"] == 100)
        & pmag_specimens["site"].isin(leger_sites)
    )
].copy()
pmag_specimens["dir_tilt_correction"].value_counts(dropna=False)

dir_tilt_correction
-1.0      522
 0.0      522
 NaN      391
 100.0    216
Name: count, dtype: int64

### Paleomagnetic samples

#### Bedding

Bedding orientations are known for the Leger panel and for the Ayn Formation at the AynC conglomerate site. For samples from other sites the bedding is unknown and is left blank, rather than given as horizontal (bed_dip of 0).

The AynC bedding is the Fisher mean of the poles to the Ayn Formation bedding planes measured within 100 m of the site in 2023 (FieldMove data in plane_2023.csv; the more distant measurements are from other exposures).

In [11]:
plane_2023 = pd.read_csv('../data/field_data/Nick_csv/plane_2023.csv', skipinitialspace=True)
aync_lat, aync_lon = SD_site_locations.loc['AynC', ['latitude', 'longitude']]
distance = 6371e3 * np.radians(np.hypot(plane_2023['latitude'] - aync_lat,
                                        (plane_2023['longitude'] - aync_lon) * np.cos(np.radians(aync_lat))))
aync_bedding = plane_2023[plane_2023['planeType'].str.contains('Bedding') & (distance < 100)]
bedding_poles = [[(dip_azimuth + 180) % 360, 90 - dip]
                 for dip_azimuth, dip in zip(aync_bedding['dipAzimuth'], aync_bedding['dip'])]
aync_bedding_pole = pmag.fisher_mean(bedding_poles)
aync_bed_dip_direction = np.round((aync_bedding_pole['dec'] + 180) % 360, 1)
aync_bed_dip = np.round(90 - aync_bedding_pole['inc'], 1)
print('AynC bedding: dip direction ' + str(aync_bed_dip_direction) + ', dip ' + str(aync_bed_dip) +
      ' (n = ' + str(aync_bedding_pole['n']) + ', alpha95 of poles = ' +
      str(np.round(aync_bedding_pole['alpha95'], 1)) + ')')

aync = pmag_samples['site'] == 'AynC'
pmag_samples.loc[aync, 'bed_dip_direction'] = aync_bed_dip_direction
pmag_samples.loc[aync, 'bed_dip'] = aync_bed_dip

bedding_known_sites = list(leger_sites) + ['AynC']
unknown_bedding = ~pmag_samples['site'].isin(bedding_known_sites)
pmag_samples.loc[unknown_bedding, ['bed_dip_direction', 'bed_dip']] = np.nan
print(str(unknown_bedding.sum()) + ' samples with unknown bedding; ' +
      str((~unknown_bedding).sum()) + ' with bedding')

AynC bedding: dip direction 327.6, dip 15.8 (n = 9, alpha95 of poles = 2.4)
173 samples with unknown bedding; 213 with bedding

#### Azimuths, geology and coordinates

MagIC requires sample azimuths between 0 and 360 degrees, and the geologic class, type, lithology, latitude and longitude in the samples table. These are taken from the sites.

In [12]:
pmag_samples['azimuth'] = pmag_samples['azimuth'].astype(float) % 360
for col in ['geologic_classes', 'geologic_types', 'lithologies']:
    pmag_samples[col] = SD_site_locations[col][pmag_samples['site']].tolist()
pmag_samples['lat'] = SD_site_locations['latitude'][pmag_samples['site']].tolist()
pmag_samples['lon'] = SD_site_locations['longitude'][pmag_samples['site']].tolist()

### Paleomagnetic specimens

All specimens were cut from their sample with a brass diamond saw. We add the method code 'SP-SAW' to indicate this.

We will also make sure all specimens refer to this study as the citation.

In [13]:
pmag_specimens['method_codes'] = pmag_specimens['method_codes'].apply(lambda x: 'SP-SAW' if pd.isna(x) else x + ':SP-SAW')

In [14]:
pmag_specimens['citations'] = pmag_specimens['citations'].fillna('This study')

In [15]:
sample_geology = pmag_samples.set_index('sample')[['geologic_classes', 'geologic_types', 'lithologies']]
for col in sample_geology.columns:
    pmag_specimens[col] = pmag_specimens['sample'].map(sample_geology[col])

#### Vector means (DE-VM)

Fits made in Demag_GUI as "line-anchored" were written with the method code DE-BFL-A. However, PmagPy calculated these fits as the vector mean of the selected steps rather than as a principal component anchored to the origin (https://github.com/PmagPy/PmagPy/issues/963). They are relabelled with the method code for a vector mean (DE-VM) so that the method code describes the calculation and the directions are unchanged. The MAD and DANG of these fits are removed, as they describe an anchored principal component rather than the vector mean. Site means that include such fits have their method codes relabelled too.

In [16]:
vector_mean = pmag_specimens['method_codes'].str.contains('DE-BFL-A', na=False)
pmag_specimens.loc[vector_mean, ['dir_mad_free', 'dir_dang']] = np.nan
pmag_specimens.loc[vector_mean, 'description'] = ('Vector mean of the selected steps; written as DE-BFL-A '
                                                  'by Demag_GUI (PmagPy issue #963)')
relabel = lambda codes: codes.replace('DE-BFL-A', 'DE-VM') if isinstance(codes, str) else codes
pmag_specimens['method_codes'] = pmag_specimens['method_codes'].apply(relabel)
pmag_sites['method_codes'] = pmag_sites['method_codes'].apply(relabel)
print(str(vector_mean.sum()) + ' specimen rows relabelled DE-VM')

269 specimen rows relabelled DE-VM

### Site VGPs, the Shaat dikes pole and site polarity

The VGPs are calculated from the site mean directions with the precise site locations. The paleomagnetic pole is the Fisher mean of the VGPs of the tilt-corrected magnetite ('mag') site means of the 51 Leger panel sites (pole_sites_list.txt, from dike_paleomagnetism.ipynb), with reversed VGPs flipped to the antipode.

The polarity of every site mean is assigned relative to this pole: normal if its VGP is in the same hemisphere as the pole and reversed otherwise. The AynC site mean is of randomly oriented conglomerate clasts and has no polarity.

In [17]:
has_dir = pmag_sites['dir_dec'].notna()

def site_vgp(row):
    a95 = row['dir_alpha95'] if pd.notna(row['dir_alpha95']) else 0.
    lon, lat, dp, dm = pmag.dia_vgp(row['dir_dec'], row['dir_inc'], a95, row['lat'], row['lon'])
    if pd.isna(row['dir_alpha95']):  # single-specimen sites have no alpha95
        dp, dm = np.nan, np.nan
    return pd.Series({'vgp_lon': lon, 'vgp_lat': lat, 'vgp_dp': dp, 'vgp_dm': dm})

pmag_sites.loc[has_dir, ['vgp_lon', 'vgp_lat', 'vgp_dp', 'vgp_dm']] = \
    pmag_sites[has_dir].apply(site_vgp, axis=1).round(1).values

In [18]:
with open("../data/pmag/pole_sites_list.txt", "r") as f:
    pole_sites_list = f.read().strip()
pole_sites = pole_sites_list.split(":")

pole_site_means = pmag_sites[pmag_sites['site'].isin(pole_sites)
                             & (pmag_sites['dir_comp_name'] == 'mag')
                             & (pmag_sites['dir_tilt_correction'] == 100)]
print(str(len(pole_site_means)) + ' tilt-corrected magnetite site means in the pole')

# polarity of the VGPs relative to the principal axis of the pole VGPs (taking its northern end)
principal = pmag.doprinc(pole_site_means[['vgp_lon', 'vgp_lat']].values.tolist())
axis = np.array(pmag.dir2cart([principal['dec'], principal['inc'], 1.]))
if principal['inc'] < 0:
    axis = -axis
pole_vgps = []
for lon, lat in pole_site_means[['vgp_lon', 'vgp_lat']].values:
    if np.dot(pmag.dir2cart([lon, lat, 1.]), axis) > 0:
        pole_vgps.append([lon, lat])
    else:
        pole_vgps.append([(lon + 180) % 360, -lat])
shaat_pole = pmag.fisher_mean(pole_vgps)
ipmag.print_pole_mean(shaat_pole)

# check against the pole calculated in dike_paleomagnetism.ipynb
with open("../data/pmag/pole_position_dict.json", "r") as f:
    published_pole = json.load(f)
print('angle to the pole of dike_paleomagnetism.ipynb: ' +
      str(round(pmag.angle([shaat_pole['dec'], shaat_pole['inc']],
                           [published_pole['dec'], published_pole['inc']])[0], 3)))

51 tilt-corrected magnetite site means in the pole
Plon: 110.1  Plat: 17.8
Number of directions in mean (n): 51
Angular radius of 95% confidence (A_95): 2.5
Precision parameter (k) estimate: 65.1
angle to the pole of dike_paleomagnetism.ipynb: 0.004

In [19]:
pole_vector = np.array(pmag.dir2cart([shaat_pole['dec'], shaat_pole['inc'], 1.]))

def polarity(row):
    if pd.isna(row['vgp_lon']) or row['site'] == 'AynC':
        return np.nan
    vgp_vector = np.array(pmag.dir2cart([row['vgp_lon'], row['vgp_lat'], 1.]))
    return 'n' if np.dot(vgp_vector, pole_vector) > 0 else 'r'

pmag_sites['dir_polarity'] = pmag_sites.apply(polarity, axis=1)
pole_site_means = pmag_sites[pmag_sites['site'].isin(pole_sites)
                             & (pmag_sites['dir_comp_name'] == 'mag')
                             & (pmag_sites['dir_tilt_correction'] == 100)]
print('pole sites: ' + str((pole_site_means['dir_polarity'] == 'r').sum()) + ' reversed, ' +
      str((pole_site_means['dir_polarity'] == 'n').sum()) + ' normal')
pmag_sites.groupby(['dir_comp_name', 'dir_tilt_correction'])['dir_polarity'].value_counts()

pole sites: 44 reversed, 7 normal

dir_comp_name  dir_tilt_correction  dir_polarity
Fit 1          0.0                  r                1
hem            0.0                  n                2
                                    r                1
               100.0                r                1
lmt            0.0                  n                1
lt             0.0                  n               62
               100.0                n               31
mag            0.0                  r               76
                                    n               12
               100.0                r               44
                                    n                7
mht            0.0                  n                3
               100.0                n                1
mt             0.0                  r               33
                                    n                6
               100.0                r                8
                                    n                2
Name: count, dtype: int64

### Paleomagnetic locations 

We need to add necessary metadata to the locations table. The following information needs to be provided:
- location_type
- geologic_classes
- lithologies
- age *or age_low and age_high*
- age_unit

In [20]:
unique_geologic_classes = pmag_sites['geologic_classes'].dropna().unique()
location_geologic_classes = ":".join(map(str, unique_geologic_classes))

unique_lithologies = pmag_sites['lithologies'].dropna().unique()
location_lithologies = ":".join(map(str, unique_lithologies))

highest_age_high = pmag_sites['age_high'].max()
lowest_age_low = pmag_sites['age_low'].min()

In [21]:
pmag_locations['location_type'] = 'Region'
pmag_locations['geologic_classes'] = location_geologic_classes
pmag_locations['lithologies'] = location_lithologies
pmag_locations['age_low'] = lowest_age_low
pmag_locations['age_high'] = highest_age_high
pmag_locations['age_unit'] = 'Ma'
pmag_locations['lat_s'] = pmag_sites['lat'].min()
pmag_locations['lat_n'] = pmag_sites['lat'].max()
pmag_locations['lon_w'] = pmag_sites['lon'].min()
pmag_locations['lon_e'] = pmag_sites['lon'].max()
# all sites of the study; the pole row below lists only the sites of the pole
pmag_locations['sites'] = ":".join(pmag_sites['site'].unique())
pmag_locations

,analysts,citations,lat_n,lat_s,location,lon_e,lon_w,location_type,geologic_classes,lithologies,age_low,age_high,age_unit,sites
location name,,,,,,,,,,,,,,
Zalawt plain,NaN,This study,17.1897,17.0336,Zalawt plain,55.0304,54.7669,Region,Sedimentary:Igneous:Metamorphic,Diamictite:Felsic Dike:Mafic Dike:Amphibolite:...,660,815,Ma,AynC:S100:S101:S102:S103:S104:S105:S106:S107:S...

#### Shaat dikes paleomagnetic pole

The pole is added to the locations table as a second row, whose sites are the 51 Leger panel sites of the pole; the first row lists all sites of the study. The mean direction is of the tilt-corrected magnetite site means with reversed directions flipped. The paleolatitude is that of the study's reference location (17.1°N, 54.9°E; Shaat_location in dike_paleomagnetism.ipynb) with its uncertainty given as A95. The reversal test is class B of McFadden and McElhinny (1990) and the conglomerate test is on 16 clasts of the Ayn Formation diamictite (dike_paleomagnetism.ipynb).

In [22]:
reference_lat, reference_lon = 17.1, 54.9
paleolat = 90 - pmag.angle([shaat_pole['dec'], shaat_pole['inc']], [reference_lon, reference_lat])[0]

mean_direction = pmag.fisher_mean(pmag.flip(pole_site_means[['dir_dec', 'dir_inc']].values.tolist(),
                                            combine=True))
n_reversed = (pole_site_means['dir_polarity'] == 'r').sum()

pole_row = {
    "location": pmag_locations['location'].iloc[0],
    "location_type": "Region",
    "geologic_classes": ":".join(pole_site_means['geologic_classes'].unique()),
    "lithologies": ":".join(sorted(pole_site_means['lithologies'].unique())),
    "lat_s": pole_site_means['lat'].min(),
    "lat_n": pole_site_means['lat'].max(),
    "lon_w": pole_site_means['lon'].min(),
    "lon_e": pole_site_means['lon'].max(),
    "age": 726,
    "age_low": pole_site_means['age_low'].min(),
    "age_high": pole_site_means['age_high'].max(),
    "age_unit": "Ma",
    "result_name": "Shaat Dikes Paleomagnetic Pole",
    "sites": pole_sites_list,
    "dir_tilt_correction": 100,
    "dir_dec": np.round(mean_direction['dec'], 1),
    "dir_inc": np.round(mean_direction['inc'], 1),
    "dir_alpha95": np.round(mean_direction['alpha95'], 1),
    "dir_k": np.round(mean_direction['k'], 1),
    "dir_n_sites": len(pole_site_means),
    "pole_lon": np.round(shaat_pole['dec'], 3),
    "pole_lat": np.round(shaat_pole['inc'], 3),
    "pole_alpha95": np.round(shaat_pole['alpha95'], 3),
    "pole_r": np.round(shaat_pole['r'], 3),
    "pole_k": np.round(shaat_pole['k'], 3),
    "pole_n_sites": shaat_pole['n'],
    "pole_comp_name": "tilt-corrected magnetite component",
    "pole_reversed_perc": np.round(100 * n_reversed / len(pole_site_means), 1),
    "paleolat": np.round(paleolat, 1),
    "paleolat_sigma": np.round(shaat_pole['alpha95'], 1),
    "reversal_test": "Rb",
    "conglomerate_test": "+",
    "plate_blocks": "Arabian Plate",
    "method_codes": "DE-FM:DA-DIR-TILT",
    "citations": "This study",
    "description": ("Fisher mean of the VGPs of the tilt-corrected magnetite site means of the Leger "
                    "panel, reversed VGPs flipped. Paleolatitude at 17.1 N, 54.9 E with A95 as its "
                    "uncertainty."),
}
pmag_locations = pd.concat([pmag_locations, pd.DataFrame([pole_row])], ignore_index=True)
pmag_locations.T

,0,1
analysts,NaN,NaN
citations,This study,This study
lat_n,17.1897,17.1892
lat_s,17.0336,17.1049
location,Zalawt plain,Zalawt plain
lon_e,55.0304,54.9628
lon_w,54.7669,54.9242
location_type,Region,Region
geologic_classes,Sedimentary:Igneous:Metamorphic,Igneous
lithologies,Diamictite:Felsic Dike:Mafic Dike:Amphibolite:...,Felsic Dike:Mafic Dike
age_low,660,726
age_high,815,735
age_unit,Ma,Ma
sites,AynC:S100:S101:S102:S103:S104:S105:S106:S107:S...,S101:S107:SD36:SD37:SD38:SD39:SD40:SD43:SD44:S...
age,NaN,726.0
result_name,NaN,Shaat Dikes Paleomagnetic Pole
dir_tilt_correction,NaN,100.0
dir_dec,NaN,80.5
dir_inc,NaN,56.5
dir_alpha95,NaN,2.0
dir_k,NaN,98.2
dir_n_sites,NaN,51.0
pole_lon,NaN,110.096
pole_lat,NaN,17.783
pole_alpha95,NaN,2.49
pole_r,NaN,50.232
pole_k,NaN,65.087
pole_n_sites,NaN,51.0
pole_comp_name,NaN,tilt-corrected magnetite component
pole_reversed_perc,NaN,86.3
paleolat,NaN,37.5
paleolat_sigma,NaN,2.5
reversal_test,NaN,Rb
conglomerate_test,NaN,+
plate_blocks,NaN,Arabian Plate
method_codes,NaN,DE-FM:DA-DIR-TILT
description,NaN,Fisher mean of the VGPs of the tilt-corrected ...

### Ages

The age of the Shaat dikes is constrained by the 726.1 ± 0.4 Ma ID-TIMS U-Pb zircon date of the Leger Granite (Bowring et al., 2007, https://doi.org/10.2475/10.2007.01), with which the dikes were broadly comagmatic, and by LA-ICPMS U-Pb zircon dates of two felsic dikes (this study).

In [23]:
ages = pd.DataFrame([
    {"location": pmag_locations['location'].iloc[0], "age": 726.1, "age_sigma": 0.4, "age_unit": "Ma",
     "method_codes": "GM-UPB", "citations": "10.2475/10.2007.01",
     "description": "Leger Granite, U-Pb zircon ID-TIMS (Bowring et al., 2007); the Shaat dikes and "
                    "Leger Granite were broadly comagmatic"},
    {"location": pmag_locations['location'].iloc[0], "site": "SD39", "age": 725, "age_sigma": 9,
     "age_unit": "Ma", "method_codes": "GM-UPB", "citations": "This study",
     "description": "Felsic dike, U-Pb zircon LA-ICPMS"},
    {"location": pmag_locations['location'].iloc[0], "site": "SD50", "age": 727, "age_sigma": 16,
     "age_unit": "Ma", "method_codes": "GM-UPB", "citations": "This study",
     "description": "Felsic dike, U-Pb zircon LA-ICPMS"},
])
ages

,location,age,age_sigma,age_unit,method_codes,citations,description,site
0,Zalawt plain,726.1,0.4,Ma,GM-UPB,10.2475/10.2007.01,"Leger Granite, U-Pb zircon ID-TIMS (Bowring et...",NaN
1,Zalawt plain,725.0,9.0,Ma,GM-UPB,This study,"Felsic dike, U-Pb zircon LA-ICPMS",SD39
2,Zalawt plain,727.0,16.0,Ma,GM-UPB,This study,"Felsic dike, U-Pb zircon LA-ICPMS",SD50

### Paleomagnetic data enhanced table save

In [24]:
pmag_contribution.tables['measurements'].df = pmag_measurements
pmag_contribution.tables['specimens'].df = pmag_specimens
pmag_contribution.tables['samples'].df = pmag_samples
pmag_contribution.tables['sites'].df = pmag_sites
pmag_contribution.tables['locations'].df = pmag_locations

In [25]:
pmag_enhanced_dir = '../data/pmag/demag_enhanced'
pmag_contribution.tables['locations'].write_magic_file(dir_path=pmag_enhanced_dir,custom_name = "locations.txt")
pmag_contribution.tables['sites'].write_magic_file(dir_path=pmag_enhanced_dir,custom_name = "sites.txt")
pmag_contribution.tables['samples'].write_magic_file(dir_path=pmag_enhanced_dir,custom_name = "samples.txt")
pmag_contribution.tables['specimens'].write_magic_file(dir_path=pmag_enhanced_dir,custom_name = "specimens.txt")
pmag_contribution.tables['measurements'].write_magic_file(dir_path=pmag_enhanced_dir,custom_name = "measurements.txt")
cb.MagicDataFrame(dtype='ages', df=ages).write_magic_file(dir_path=pmag_enhanced_dir, custom_name="ages.txt")

-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/locations.txt
-I- 2 records written to locations file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/sites.txt
-I- 301 records written to sites file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/samples.txt
-I- 386 records written to samples file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/specimens.txt
-I- 1651 records written to specimens file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/measurements.txt

-I- 9099 records written to measurements file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/ages.txt
-I- 3 records written to ages file

'/Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/demag_enhanced/ages.txt'

## Rock magnetic data

The rock magnetic data are within a specimens table and a measurements table.

In [26]:
ipmag.unpack_magic('../data/pmag/rockmag/Oman_23_24.TXT', dir_path='../data/pmag/rockmag')

working on:

 'specimens\r'
19  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag/specimens.txt
  data put in  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag/specimens.txt
working on:  'measurements\r'

20326  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag/measurements.txt
  data put in  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag/measurements.txt

True

In [27]:
rmag_dir_path = '../data/pmag/rockmag'
rmag_contribution = cb.Contribution(rmag_dir_path)
rmag_measurements = rmag_contribution.tables['measurements'].df
rmag_specimens = rmag_contribution.tables['specimens'].df
rmag_measurements.head(1)

,analysts,aniso_s,aniso_type,citations,contribution_id,derived_value,description,dir_csd,dir_dec,dir_inc,display_order,experiment,external_database_ids,files,hyst_charging_mode,hyst_loop,hyst_sweep_rate,instrument_codes,inversion_height,inversion_residuals,magn_b_111,magn_b_111_sigma,magn_b_x,magn_b_x_sigma,magn_b_xyz_sigma,magn_b_y,magn_b_y_sigma,magn_b_z,magn_b_z_sigma,magn_induction,magn_mass,magn_moment,magn_r2_det,magn_uncal,magn_volume,magn_x,magn_x_sigma,magn_xyz_sigma,magn_y,magn_y_sigma,magn_z,magn_z_sigma,meas_duration,meas_field_ac,meas_field_ac_phi,meas_field_ac_theta,meas_field_dc,meas_field_dc_phi,meas_field_dc_theta,meas_freq,meas_n_orient,meas_orient_phi,meas_orient_theta,meas_pos_x,meas_pos_y,meas_pos_z,meas_temp,meas_temp_change,measurement,method_codes,quality,result_type,row_id,sequence,software_packages,specimen,standard,susc_chi_mass,susc_chi_qdr_mass,susc_chi_qdr_volume,susc_chi_volume,timestamp,treat_ac_field,treat_ac_field_dc_off,treat_ac_field_dc_on,treat_ac_field_decay_rate,treat_dc_field,treat_dc_field_ac_off,treat_dc_field_ac_on,treat_dc_field_decay_rate,treat_dc_field_phi,treat_dc_field_theta,treat_mw_integral,treat_mw_power,treat_mw_step,treat_mw_time,treat_step_num,treat_temp,treat_temp_dc_off,treat_temp_dc_on,treat_temp_decay_rate
measurement name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
IRM-VSM4-LP-HYS-241942-1,NaN,NaN,NaN,This study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IRM-VSM4-LP-HYS-241942,NaN,NaN,NaN,NaN,NaN,IRM-VSM4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294.0,NaN,IRM-VSM4-LP-HYS-241942-1,LP-HYS,g,NaN,NaN,NaN,NaN,SD38-3,u,NaN,NaN,NaN,NaN,2024:10:25:10:33:27.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The specimens prepared from rock magnetism should have been given unique names relative to the samples. We will append an 'r' to the sample name to indicate that it was the chip that was prepared for rock magnetic experiments.

In [28]:
rmag_specimens['specimen'] = rmag_specimens['specimen'].apply(lambda x: x + 'r' if isinstance(x, str) else x)
rmag_measurements['specimen'] = rmag_measurements['specimen'].apply(lambda x: x + 'r' if isinstance(x, str) else x)

Specimen SD18-3r is assigned to sample SD38-3 in the IRM database export, so its sample is ambiguous. It has only a mass and volume (no measurements) and is removed.

In [29]:
rmag_specimens = rmag_specimens[rmag_specimens['specimen'] != 'SD18-3r']
rmag_measurements = rmag_measurements[rmag_measurements['specimen'] != 'SD18-3r']
print((rmag_specimens['specimen'] == 'SD18-3r').sum(), (rmag_measurements['specimen'] == 'SD18-3r').sum())

0 0

MagIC requires the geologic class, type and lithology in the specimens table. For the rock magnetic specimens they are taken from their samples.

In [30]:
for col in ['geologic_classes', 'geologic_types', 'lithologies']:
    rmag_specimens[col] = rmag_specimens['sample'].map(sample_geology[col])
rmag_specimens[['specimen', 'sample', 'geologic_types', 'lithologies']].head()

              specimen  sample geologic_types lithologies
specimen name
SD38-3         SD38-3r  SD38-3  Volcanic Dike  Mafic Dike
SD47-4         SD47-4r  SD47-4  Volcanic Dike  Mafic Dike
SD49-1         SD49-1r  SD49-1  Volcanic Dike  Mafic Dike
SD56-3         SD56-3r  SD56-3  Volcanic Dike  Mafic Dike
SD58-1         SD58-1r  SD58-1  Volcanic Dike  Mafic Dike

In [31]:
rmag_measurements['timestamp'] = pd.to_datetime(
    rmag_measurements['timestamp'],
    format='%Y:%m:%d:%H:%M:%S.%f',
    errors='raise'
)
rmag_measurements.head(1)

,analysts,aniso_s,aniso_type,citations,contribution_id,derived_value,description,dir_csd,dir_dec,dir_inc,display_order,experiment,external_database_ids,files,hyst_charging_mode,hyst_loop,hyst_sweep_rate,instrument_codes,inversion_height,inversion_residuals,magn_b_111,magn_b_111_sigma,magn_b_x,magn_b_x_sigma,magn_b_xyz_sigma,magn_b_y,magn_b_y_sigma,magn_b_z,magn_b_z_sigma,magn_induction,magn_mass,magn_moment,magn_r2_det,magn_uncal,magn_volume,magn_x,magn_x_sigma,magn_xyz_sigma,magn_y,magn_y_sigma,magn_z,magn_z_sigma,meas_duration,meas_field_ac,meas_field_ac_phi,meas_field_ac_theta,meas_field_dc,meas_field_dc_phi,meas_field_dc_theta,meas_freq,meas_n_orient,meas_orient_phi,meas_orient_theta,meas_pos_x,meas_pos_y,meas_pos_z,meas_temp,meas_temp_change,measurement,method_codes,quality,result_type,row_id,sequence,software_packages,specimen,standard,susc_chi_mass,susc_chi_qdr_mass,susc_chi_qdr_volume,susc_chi_volume,timestamp,treat_ac_field,treat_ac_field_dc_off,treat_ac_field_dc_on,treat_ac_field_decay_rate,treat_dc_field,treat_dc_field_ac_off,treat_dc_field_ac_on,treat_dc_field_decay_rate,treat_dc_field_phi,treat_dc_field_theta,treat_mw_integral,treat_mw_power,treat_mw_step,treat_mw_time,treat_step_num,treat_temp,treat_temp_dc_off,treat_temp_dc_on,treat_temp_decay_rate
measurement name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
IRM-VSM4-LP-HYS-241942-1,NaN,NaN,NaN,This study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IRM-VSM4-LP-HYS-241942,NaN,NaN,NaN,NaN,NaN,IRM-VSM4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294.0,NaN,IRM-VSM4-LP-HYS-241942-1,LP-HYS,g,NaN,NaN,NaN,NaN,SD38-3r,u,NaN,NaN,NaN,NaN,2024-10-25 10:33:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In the IRM database export, the backfield measurements (LP-BCR-BF) have the measurement temperature (294 K) in the 'standard' column and no meas_temp. The value is moved to meas_temp and 'standard' is set to 'u', as in the hysteresis measurements.

In [32]:
misplaced_temp = (pd.to_numeric(rmag_measurements['standard'], errors='coerce').notna()
                  & rmag_measurements['meas_temp'].isna())
rmag_measurements.loc[misplaced_temp, 'meas_temp'] = pd.to_numeric(rmag_measurements.loc[misplaced_temp, 'standard'])
rmag_measurements.loc[misplaced_temp, 'standard'] = 'u'
print(str(misplaced_temp.sum()) + ' measurements corrected')

900 measurements corrected

In [33]:
rmag_contribution.tables['measurements'].df = rmag_measurements
rmag_contribution.tables['specimens'].df = rmag_specimens

rmag_enhanced_dir = '../data/pmag/rockmag_enhanced'
rmag_contribution.tables['specimens'].write_magic_file(dir_path=rmag_enhanced_dir,custom_name = "specimens.txt")
rmag_contribution.tables['measurements'].write_magic_file(dir_path=rmag_enhanced_dir,custom_name = "measurements.txt")

-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag_enhanced/specimens.txt
-I- 18 records written to specimens file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag_enhanced/measurements.txt

-I- 20326 records written to measurements file

'/Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/rockmag_enhanced/measurements.txt'

## Merge rock magnetic and paleomagnetic MagIC tables

The specimens and measurements tables can be combined.

In [34]:
ipmag.combine_magic([rmag_enhanced_dir + '/specimens.txt',
                     pmag_enhanced_dir + '/specimens.txt'], 
                    outfile = pmag_rmag_dir + '/specimens.txt',
                    magic_table='specimens')

ipmag.combine_magic([rmag_enhanced_dir + '/measurements.txt',
                     pmag_enhanced_dir + '/measurements.txt'], 
                    outfile = pmag_rmag_dir + '/measurements.txt',
                    magic_table='measurements')

-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/specimens.txt
-I- 1669 records written to specimens file
-I- overwriting /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/measurements.txt

-I- 29425 records written to measurements file

'/Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/measurements.txt'

The samples, sites, locations and ages tables will be the ones from the pmag data as they have not been updated in conjunction with the rock magnetic data.

In [35]:
shutil.copy(pmag_enhanced_dir + '/locations.txt', pmag_rmag_dir + '/locations.txt')
shutil.copy(pmag_enhanced_dir + '/sites.txt', pmag_rmag_dir + '/sites.txt')
shutil.copy(pmag_enhanced_dir + '/samples.txt', pmag_rmag_dir + '/samples.txt')
shutil.copy(pmag_enhanced_dir + '/ages.txt', pmag_rmag_dir + '/ages.txt')

'../data/pmag/ages.txt'

A new MagIC contribution can be made from the combined files. MagIC validates the file when it is uploaded, so validation through the MagIC API is not run here.

In [36]:
ipmag.upload_magic(dir_path=pmag_rmag_dir, input_dir_path=pmag_rmag_dir, validate=False)

-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/locations.txt file successfully read in
2  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/locations.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/samples.txt file successfully read in
386  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/samples.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/specimens.txt file successfully read in
1669  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/specimens.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/sites.txt file successfully read in
301  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/sites.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/ages.txt file successfully read in
3  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/ages.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt

/Users/unimos/0000_Github/PmagPy/pmagpy/ipmag.py:5446: DtypeWarning: Columns (0: software_packages, 1: timestamp) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_type,sep='\t',header=1)

-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/measurements.txt file successfully read in

29425  records written to file  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
-I- /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/measurements.txt written to  /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/upload.txt
Finished preparing upload file: /Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/Zalawt-plain_22.Oct.2026.txt

('/Users/unimos/0000_Github/2025_Oman_Paleogeography/data/pmag/Zalawt-plain_22.Oct.2026.txt',
 {},
 None,
 None)